# Generated by Django 4.2.3 on 2023-07-31 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0002_alter_employee_joining_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
